### ISSUE TITLE
add API for initializing a new `List`

### ISSUE THREAD

**Issue by dtbuchholz** [ralexstokes/ssz-rs#20]
Issue raised in comment from [ethereum-consensus](https://github.com/ralexstokes/ethereum-consensus/pull/106/files/26e49f75aeb4038459a4a76a437ffc309f7ce510#r888584848)

Idea is to avoid something like the below and allow for a new `List` to be initialized without allocating a `Vec` and then converting into a `List`.
```
let rotate_participation = vec![ParticipationFlags::default(); state.validators.len()];
    state.current_epoch_participation = rotate_participation
        .try_into()
        .expect("should convert from Vec to List");
```
For example, add impl of `new` for something like `List<T>::new(capacity: usize)` (or, in the example above, just allow for `state.current_epoch_participation = List::<u8>::new(state.validators.len())`.

Based on some initial research, I'm not quite sure how to do this since `List` obviously takes `List<T, N>` where `N` is a `const usize`...so `List<T>` would be invalid. And without knowing `N` at compile time, that introduces concepts like raw pointers,  `unsafe` rust, `Box`, `Arc`, etc. that I couldn't figure out how to use or if they even solve this problem.

**Comment by ralexstokes** [comment]
I think we can just use this?

https://github.com/ralexstokes/ssz-rs/blob/main/ssz-rs/src/list.rs#L110

```rust
let M;
let N;
assert!(M <= N);
let inner = vec![T; M];
let list = List::<T, N>::try_from(inner).unwrap();
```

**Comment by ralexstokes** [comment]
this is a bit stale but I believe the concern was around an additional allocation of the backing `Vec` but the current implementation of `TryFrom<Vec<T>>` for `List` just takes ownership of the data, so ill close this issue
