### ISSUE TITLE
Do we have any idea to achieve a `no-std` feature of ssz-rs?

### ISSUE THREAD

**Issue by ashuralyk** [ralexstokes/ssz-rs#24]

**Comment by ralexstokes** [comment]
I think the main thing will be working around uses of types that allocate and rely on `std` features

I haven't looked myself but one way to start would be to just declare the crate `no-std` and see what the compiler doesn't like

**Comment by ashuralyk** [comment]
> I think the main thing will be working around uses of types that allocate and rely on `std` features
> 
> I haven't looked myself but one way to start would be to just declare the crate `no-std` and see what the compiler doesn't like

I see

**Comment by ralexstokes** [comment]
#25 sets out to handle this, will close this issue
