### ISSUE TITLE
migrate to `alloy` primitives

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ssz-rs#94]
https://github.com/alloy-rs/core/tree/main/crates/primitives

this is a bigger task but should pay dividends in the long run to unify foundations across the communities

**Comment by ralexstokes** [comment]
a big one is the `U256` implementation

another one could be the `Node` type in the merkle code

and possibly using the bytes primitives here

**Comment by PatStiles** [comment]
Interested

**Comment by ralexstokes** [comment]
@PatStiles you could start by removing the `U256` defined currently and just supporting `ruint`'s U256 type, implementing the various SSZ traits for it in this repo

**Comment by ralexstokes** [comment]
mostly handled in #113
